apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camel-ingress
  namespace: camel
spec:
  ingressClassName: nginx
  rules:
    - host: camel.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: camel-api
                port:
                  number: 80
